### ISSUE TITLE
User role

### ISSUE THREAD

**Issue by Eronne** [FashionData/maestro#25]
**Is your feature request related to a problem? Please describe.**
We don't have any current way to attribute roles to users.

**Describe the solution you'd like**
Add a way to precise role into users-listing page

**Comment by romone22** [comment]
Here is a suggestion of role listing : 
- Super Admin (Code = 9) : Can manage the full Maestro application. Needed to create account
- Admin (Code = 7 ) : Can the account attached to this admin, the users and documents attached to the admin account
- Writer (Code = 5) : Can create/update/delete and comment documents in the Maestro application
- User (Code = 3) : Can launch/execute and comment previously created maestro document
- Viewer (Code = 1): Can only view and comment previously created maestro document
- Candidate (Code = 0) : Ask autorisation to get at least the Viewer role for an maestro account

Only Super Admin and Admin can manage users. 

Those roles will be attached to the user claims combine with the associated account ID.
Because we can put a lot of data into the user claims, the account roles and authorization should be concateneted (RoleCoce-AccountID) and set in a array named "access"

Example :
Romain is Super Admin of the account 000010, Writer of the account 000040 and candidat for the account 000090.
The Romain's firebase User Claim will be set with the attribute access : 
`access = ["9-000010","5-000040","0-000090"]`

**Comment by Eronne** [comment]
@Liinkiing #42 Provides this isn't it?

**Comment by Liinkiing** [comment]
> @Liinkiing #42 Provides this isn't it?

Exactly 👍
